language: python
python:
  - "3.6"
install:
  - pip install codecov nosexcover
  - pip install -r requirements_tests.txt
  - pip uninstall -y pytest
  - snips-nlu download-all-languages
script:
  - python -m nose --with-doctest --with-xcoverage --cover-package=reminder
after_success:
  - codecov